global:
  default_git_branch: master
  env:
  - name: PROFILE_DIR
    value@tlang: fs.Join dukkha.WorkDir "build" "test-profile"
  values:
    cmd:
      run_ctr@presets?str|tmpl: templates/run-ctr.tmpl

renderers:
- http:presets:
    alias: presets
    cache:
      enabled: true
      timeout: 2h
    base_url: https://raw.githubusercontent.com/arhat-dev/dukkha-presets/master

  env:
    enable_exec: true

tools:
  workflow:
  - name: local
  - name: in-ctr

  golang:
  - name: local
  - name: in-ctr
    cmd@tmpl#use-spec:
      template: |-
        {{- include "golang.cmd.ctr" . -}}
      include:
      - text@presets?str: templates/image/flavored-tag.tmpl
      - text@presets?str: golang/cmd/ctr.tmpl
      variables:
        version: "1.18"

workflow:run:
- name: tidy
  env:
  - name: GOPROXY
    value: direct
  - name: GOSUMDB
    value: "off"
  jobs:
  - shell: |-
      go mod tidy
      cd benchmark && go mod tidy

- name: lint
  matrix:
    include:
    - tool: [editorconfig-checker]
      config:
      - __@presets#cached-file?str: tools/editorconfig-checker/config.json
    - tool: [shellcheck]
    - tool: [yamllint]
      config:
      - __@presets#cached-file?str: tools/yamllint/config.yaml
    - tool: [golangci-lint]
      config:
      - __@presets#cached-file?str: tools/golangci-lint/config.yaml
  jobs:
  - cmd@presets?str|tmpl#use-spec: tools/presets.tmpl

- name: test
  jobs:
  - task:
      ref: golang:test(rs)
      matrix_filter: {}
  - task:
      ref: golang:test(benchmark)
      matrix_filter: {}

- name: report
  matrix:
    tool:
    - sonar-scanner
  jobs:
  # only run sonar scan on linux and darwin during CI
  - cmd@presets?str|tmpl#use-spec: tools/presets.tmpl
    continue_on_error: true

golang:test:
- name: rs
  __@tmpl#use-spec:
    template: |-
      {{- include "golang.test.pkg" . -}}
    include:
    - text@presets?str: golang/test/pkg.tmpl
  matrix:
    pkg@tlang: |-
      (eval.Shell "go list ./...").Stdout \
        | removePrefix ((eval.Shell "go list -m").Stdout | trimSuffix "\n") \
        | addPrefix "- "
  hooks:
    before:
    - shell: mkdir -p ${PROFILE_DIR}

- name: benchmark
  matrix:
    pkg:
    - ./
  chdir: ./benchmark
  hooks:
    before:
    - idle@tlang: mkdir "-p" env.PROFILE_DIR
  cgo:
    enabled: true
  race@tlang: ne host.kernel "windows"
  profile:
    output_dir@tlang: env.PROFILE_DIR
    coverage:
      enabled: true
    memory:
      enabled: true
    cpu:
      enabled: true
  benchmark:
    enabled: true
  json_output_file@tlang: fs.Join env.PROFILE_DIR "result-benchmark.json"
  verbose: true
  path: ./
