name: CI

# yamllint disable-line rule:truthy
on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    tags:
    - v*

env:
  GO111MODULE: "on"

defaults:
  run:
    shell: bash

jobs:
  stylecheck:
    uses: arhat-dev/dukkha-presets/.github/workflows/stylecheck.yml@master
  test:
    uses: arhat-dev/dukkha-presets/.github/workflows/test.yml@master
    with:
      matrix: |-
        {
          "os": [
            "macos-latest",
            "windows-latest",
            "ubuntu-latest"
          ],
          "go": [
            "1.16.x",
            "1.17.x"
          ]
        }
